// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

public class SecondGUI : MonoBehaviour {
	
	private bool secondGUI = true;
	public GUIStyle style;
	
	private Texture btnTexture;
	
	// Use this for initialization
	void Start () {
		
	}
	
	// Update is called once per frame
	void Update () {
		
	}
	
	void OnGUI () {
		Debug.Log (secondGUI);
		if(secondGUI)
		{
			Rect rectangle = new Rect(20, (Screen.height/3), Screen.width, Screen.height);
			GUILayout.BeginArea (rectangle);
			GUILayout.Label("Dinozens of the Pangea went about their days … dropping off their kids at dino school. Going to dino work. And Eating dino food. /n But everything was about to change…", style);
			if(GUILayout.Button ("Next"))
			{
				secondGUI = false;
				Application.LoadLevel("TutorialScene");
			}
			GUILayout.EndArea ();
		}
		Rect rectangle2 = new Rect(10,10,100,100);
		string text1 = "Skip To Menu";
		if (GUI.Button(rectangle2, text1))
		{
			secondGUI = false;
			Application.LoadLevel("MainMenu");
		}
		
	}
}
